### ISSUE TITLE
Incorrect port in redirect URL

### ISSUE THREAD

**Issue by twitu** [megabit-labs/pathways#15]
https://github.com/dush-t/pathways/blob/5bbe603089919112fa749246c8d9f782bd3d457b/client/src/components/GithubAuth/GithubAuth.js#L24
The port should be changed to `3003` because docker is doing a mapping.
https://github.com/dush-t/pathways/blob/5bbe603089919112fa749246c8d9f782bd3d457b/docker-compose.yaml#L20

**Comment by chirag-wadhwa** [comment]
For the development mode, the app runs at port 3000. If I redirect to 3003, nothing would be displayed right ???

**Comment by twitu** [comment]
This is for when the application is deployed using `docker-compose`.

**Comment by hedonhermdev** [comment]
I think we can do without the redirect port in the client side. Just change the redirect uri in the GitHub settings to however/wherever you are hosting.

**Comment by twitu** [comment]
Are you using GItHub settings to to store environment variables/secrets?
What about local dev environment?
Is this solved?

**Comment by hedonhermdev** [comment]
The oauth app you are using has a setting called “Callback URI” GitHub redirects to that URI after a successful login. For security it lets you pass the callback Uri in the login request too. If these two do not match we get an error. As we are using multiple dev environments, it was a good idea to remove the callback Uri from the login request.
