### ISSUE TITLE
Changing step type on create-edit-pathway page is not functional

### ISSUE THREAD

**Issue by dusnat** [megabit-labs/pathways#33]
Clicking on the step tag over the heading changes the tag, but the user can still see the same content-editing area.

When the tag is changed, the user should see an appropriate input in the content-editing area. These are the inputs corresponding to the step types - 

* Pathway - a single text input asking for the ID of the pathway to be used as the step.
* Shared Content - a single text input asking for the ID of the step-content to be used as the step.
* Step - the content-editing area as usual.

Note that in all cases, the `StepDataEdit` component should still remain and only the `StepContentEdit` component should be "changing", since the author will always need to enter the step metadata in the `StepDataEdit` component.

**Comment by jshreyans** [comment]
I don't think this looks too good:

![Screenshot from 2020-07-23 17-06-32](https://user-images.githubusercontent.com/41480918/88282296-e729de00-cd06-11ea-8da9-80b1818c512a.png)

**Comment by dusnat** [comment]
Make it such that if it's a step, you render the markdown from the step below this field in a non-editable way.

If it's a pathway, display relevant pathway information below this field. That should look functional and more "full"

**Comment by jshreyans** [comment]
> Make it such that if it's a step, you render the markdown from the step below this field in a non-editable way.

What step would that be? The user is essentially creating a new step right? I'm assuming you're talking about the case of a Shared Step. 

Also, wouldn't this be a bit extra? Instead, we could _describe_ what the user is actually doing by creating a shared step. Just a suggestion.

**Comment by dusnat** [comment]
I'm talking about a shared step. A shared step is a step originally written in some other pathway, that the author of the current pathway wants to include. The author must have an idea of what step he is including, so I wouldn't call it extra.

> Instead, we could describe what the user is actually doing by creating a shared step. Just a suggestion.

That is supposed to be done _before_ the user enters a step id, using some illustration in that huge empty space. Once the user enters a stepID, it's better to show him what that step contains.

**Comment by jshreyans** [comment]
All right so when the user types in the ID of the step, they can see the markdown for that step below and we can use the Preview button to render this markdown. Fine, that should solve the issue.
