### ISSUE TITLE
Cannot Add Pathway Step

### ISSUE THREAD

**Issue by hedonhermdev** [megabit-labs/pathways#54]
Pathway steps fail to render because of incorrect graphql schema.

![Screenshot 2020-12-27 at 3 31 33 PM](https://user-images.githubusercontent.com/23262887/103168422-2087ec00-4859-11eb-975c-ab93ee4c9983.png)

This is again because of updates in the GraphQL schema on the server. Make necessary changes in the graphql query on the client to fix this.

**Comment by psrth** [comment]
resolved with this [commit](https://github.com/megabit-labs/pathways/commit/87992d9e10635c118c4d78b37157768b98358cd3). also, went through the entire codebase to try and spot the same issue anywhere else — should work fine now.
